/// Flutter icons AppIconFont
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIconFont
///      fonts:
///       - asset: fonts/AppIconFont.ttf
///
/// 
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class AppIconFont {
  AppIconFont._();

  static const _kFontFam = 'AppIconFont';

  static const IconData star = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData cancel = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData star_empty = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData ok = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData female = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData male = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData at = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData left = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData right = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData mail = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData clock = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData up_open = const IconData(0xf005, fontFamily: _kFontFam);
  static const IconData right_open = const IconData(0xf006, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xf008, fontFamily: _kFontFam);
  static const IconData th_list = const IconData(0xf009, fontFamily: _kFontFam);
  static const IconData th_thumb = const IconData(0xf00a, fontFamily: _kFontFam);
  static const IconData th_thumb_empty = const IconData(0xf00b, fontFamily: _kFontFam);
  static const IconData coverflow = const IconData(0xf00c, fontFamily: _kFontFam);
  static const IconData paper_plane = const IconData(0xf01d, fontFamily: _kFontFam);
  static const IconData ccw = const IconData(0xf025, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xf031, fontFamily: _kFontFam);
  static const IconData mobile = const IconData(0xf034, fontFamily: _kFontFam);
  static const IconData videocam = const IconData(0xf03a, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xf03d, fontFamily: _kFontFam);
  static const IconData mic_off = const IconData(0xf047, fontFamily: _kFontFam);
  static const IconData mic = const IconData(0xf048, fontFamily: _kFontFam);
  static const IconData users = const IconData(0xf064, fontFamily: _kFontFam);
  static const IconData cancel_circled = const IconData(0xf06e, fontFamily: _kFontFam);
  static const IconData link = const IconData(0xf07b, fontFamily: _kFontFam);
  static const IconData export_icon = const IconData(0xf081, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xf4ac, fontFamily: _kFontFam);
  static const IconData folder_open_empty = const IconData(0xf4c2, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xf4f7, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xf50d, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xf512, fontFamily: _kFontFam);
  static const IconData lock_open = const IconData(0xf513, fontFamily: _kFontFam);
  static const IconData fire = const IconData(0xf525, fontFamily: _kFontFam);
  static const IconData spinner2 = const IconData(0xf529, fontFamily: _kFontFam);
}
